--- #YAML:1.0
name:               DateTime-Format-Oracle
version:            0.06
abstract:           Parse and format Oracle dates and timestamps
author:
    - Nathan Gray <kolibrie@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Convert::NLS_DATE_FORMAT:  0.03
    DateTime:             0
    DateTime::Format::Builder:  0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
